# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors/CMakeFiles /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named memoryAllocator

# Build rule for target.
memoryAllocator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memoryAllocator
.PHONY : memoryAllocator

# fast build rule for target.
memoryAllocator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/build
.PHONY : memoryAllocator/fast

src/FreeListAllocator.o: src/FreeListAllocator.cpp.o
.PHONY : src/FreeListAllocator.o

# target to build an object file
src/FreeListAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/FreeListAllocator.cpp.o
.PHONY : src/FreeListAllocator.cpp.o

src/FreeListAllocator.i: src/FreeListAllocator.cpp.i
.PHONY : src/FreeListAllocator.i

# target to preprocess a source file
src/FreeListAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/FreeListAllocator.cpp.i
.PHONY : src/FreeListAllocator.cpp.i

src/FreeListAllocator.s: src/FreeListAllocator.cpp.s
.PHONY : src/FreeListAllocator.s

# target to generate assembly for a file
src/FreeListAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/FreeListAllocator.cpp.s
.PHONY : src/FreeListAllocator.cpp.s

src/LinearAllocator.o: src/LinearAllocator.cpp.o
.PHONY : src/LinearAllocator.o

# target to build an object file
src/LinearAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/LinearAllocator.cpp.o
.PHONY : src/LinearAllocator.cpp.o

src/LinearAllocator.i: src/LinearAllocator.cpp.i
.PHONY : src/LinearAllocator.i

# target to preprocess a source file
src/LinearAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/LinearAllocator.cpp.i
.PHONY : src/LinearAllocator.cpp.i

src/LinearAllocator.s: src/LinearAllocator.cpp.s
.PHONY : src/LinearAllocator.s

# target to generate assembly for a file
src/LinearAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/LinearAllocator.cpp.s
.PHONY : src/LinearAllocator.cpp.s

src/PoolAllocator.o: src/PoolAllocator.cpp.o
.PHONY : src/PoolAllocator.o

# target to build an object file
src/PoolAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/PoolAllocator.cpp.o
.PHONY : src/PoolAllocator.cpp.o

src/PoolAllocator.i: src/PoolAllocator.cpp.i
.PHONY : src/PoolAllocator.i

# target to preprocess a source file
src/PoolAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/PoolAllocator.cpp.i
.PHONY : src/PoolAllocator.cpp.i

src/PoolAllocator.s: src/PoolAllocator.cpp.s
.PHONY : src/PoolAllocator.s

# target to generate assembly for a file
src/PoolAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/PoolAllocator.cpp.s
.PHONY : src/PoolAllocator.cpp.s

src/RBFreeListAllocator.o: src/RBFreeListAllocator.cpp.o
.PHONY : src/RBFreeListAllocator.o

# target to build an object file
src/RBFreeListAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/RBFreeListAllocator.cpp.o
.PHONY : src/RBFreeListAllocator.cpp.o

src/RBFreeListAllocator.i: src/RBFreeListAllocator.cpp.i
.PHONY : src/RBFreeListAllocator.i

# target to preprocess a source file
src/RBFreeListAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/RBFreeListAllocator.cpp.i
.PHONY : src/RBFreeListAllocator.cpp.i

src/RBFreeListAllocator.s: src/RBFreeListAllocator.cpp.s
.PHONY : src/RBFreeListAllocator.s

# target to generate assembly for a file
src/RBFreeListAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/RBFreeListAllocator.cpp.s
.PHONY : src/RBFreeListAllocator.cpp.s

src/StackAllocator.o: src/StackAllocator.cpp.o
.PHONY : src/StackAllocator.o

# target to build an object file
src/StackAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/StackAllocator.cpp.o
.PHONY : src/StackAllocator.cpp.o

src/StackAllocator.i: src/StackAllocator.cpp.i
.PHONY : src/StackAllocator.i

# target to preprocess a source file
src/StackAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/StackAllocator.cpp.i
.PHONY : src/StackAllocator.cpp.i

src/StackAllocator.s: src/StackAllocator.cpp.s
.PHONY : src/StackAllocator.s

# target to generate assembly for a file
src/StackAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/StackAllocator.cpp.s
.PHONY : src/StackAllocator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memoryAllocator.dir/build.make CMakeFiles/memoryAllocator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... memoryAllocator"
	@echo "... src/FreeListAllocator.o"
	@echo "... src/FreeListAllocator.i"
	@echo "... src/FreeListAllocator.s"
	@echo "... src/LinearAllocator.o"
	@echo "... src/LinearAllocator.i"
	@echo "... src/LinearAllocator.s"
	@echo "... src/PoolAllocator.o"
	@echo "... src/PoolAllocator.i"
	@echo "... src/PoolAllocator.s"
	@echo "... src/RBFreeListAllocator.o"
	@echo "... src/RBFreeListAllocator.i"
	@echo "... src/RBFreeListAllocator.s"
	@echo "... src/StackAllocator.o"
	@echo "... src/StackAllocator.i"
	@echo "... src/StackAllocator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/spocam/Documents/GitHub/Custom-Memory-Alloactors/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

